#!/bin/sh
# Update HOST with actual value, uniquely generated by Docker on each start

su - oracle

sed -i -E "s/HOST = [^)]+/HOST = $HOSTNAME/g" $ORACLE_HOME/network/admin/listener.ora
sed -i -E "s/HOST = [^)]+/HOST = $HOSTNAME/g" $ORACLE_HOME/network/admin/tnsnames.ora

while true; do
    pmon=`ps -ef | grep pmon_$ORACLE_SID | grep -v grep`

    if [ "$pmon" == "" ]
    then
        date
        # /etc/init.d/oracle-xe start
		# $ORACLE_HOME/bin/dbshut $ORACLE_HOME
		$ORACLE_HOME/bin/dbstart $ORACLE_HOME
    fi
    sleep 1m
done;
